parameter_defaults:
  DnsServers: ['192.168.1.221']
  StorageMtu: 9000
  StorageMgmtMtu: 9000
  InternalApiMtu: 9000
  TenantMtu: 9000
  ExternalMtu: 9000
  PublicVirtualFixedIPs: [{'ip_address':'172.20.10.25'}]
  CloudDomain: bne-home.net
  # NetworkDeploymentActions: ['CREATE']
  NetworkDeploymentActions: ['CREATE','UPDATE']
  NeutronEnableDVR: false
  ExtraFirewallRules:
    '301 allow Prometheus':
      dport: 9100
      proto: tcp
      source: 172.20.0.0/16
      action: insert

  ## After Swift has been removed from the Undercloud, we can't use it to upload Swift Rings to:
  SwiftRingPutTempurl: ''
  SwiftRingGetTempurl: ''
