# This template configures each role to use a separate NIC for
# each isolated network.
# This template assumes use of network-isolation.yaml.
#
# FIXME: if/when we add functionality to heatclient to include heat
# environment files we should think about using it here to automatically
# include network-isolation.yaml.
#
# There is no longer a requirement to use net-multiple-nics-v6.yaml for
# nodes when deploying with IPv6. You may now define both an IPv4 network
# and an IPv6 network as default routes by adding both networks to the
# default_route_networks list for the Controller role in roles_data.yaml.
# Then include this environment file to use bond-with-vlans NIC configs.

parameter_defaults:
  ControllerNetworkConfigTemplate: '/home/stack/templates/nic-configs/multiple_nics.j2'
  StandaloneNetworkConfigTemplate: '/home/stack/templates/nic-configs/bonds_vlans.j2'
  ComputeNetworkConfigTemplate: '/home/stack/templates/nic-configs/compute-bridge-vlans.j2'
