parameter_defaults:
  DnsServers: ['192.168.1.221','172.20.10.22']
  StorageMtu: 9000
  StorageMgmtMtu: 9000
  InternalApiMtu: 9000
  TenantMtu: 9000
  ExternalMtu: 9000
  PublicVirtualFixedIPs: [{'ip_address':'172.20.10.25'}]
  CloudDomain: bne-home.net
<<<<<<< HEAD
  # NetworkDeploymentActions: ['CREATE']
  NetworkDeploymentActions: ['CREATE','UPDATE']
  NeutronEnableDVR: false
=======
  NetworkDeploymentActions: ['CREATE']
  # NetworkDeploymentActions: ['CREATE','UPDATE']
  # ComputeNetworkDeploymentActions: ['CREATE','UPDATE']
  NeutronEnableDVR: false
  BondInterfaceOvsOptions: bond_mode=balance-slb
>>>>>>> 22080dc0069fd913fc2092ebad07488da11e284c
  ExtraFirewallRules:
    '301 allow Prometheus':
      dport: 9100
      proto: tcp
      source: 172.20.0.0/16
      action: insert

  ## After Swift has been removed from the Undercloud, we can't use it to upload Swift Rings to:
  SwiftRingPutTempurl: ''
  SwiftRingGetTempurl: ''
