parameter_defaults:
  ControlPlaneVipData:
    fixed_ips:
    - ip_address: 192.168.24.18
    name: control_virtual_ip
    network:
      tags:
      - 192.168.24.0/24
    subnets:
    - ip_version: 4
  VipPortMap:
    external:
      ip_address: 172.20.10.16
      ip_address_uri: 172.20.10.16
      ip_subnet: 172.20.10.16/16
    internal_api:
      ip_address: 172.16.2.81
      ip_address_uri: 172.16.2.81
      ip_subnet: 172.16.2.81/24
    storage:
      ip_address: 172.16.1.7
      ip_address_uri: 172.16.1.7
      ip_subnet: 172.16.1.7/24
    storage_mgmt:
      ip_address: 172.16.3.216
      ip_address_uri: 172.16.3.216
      ip_subnet: 172.16.3.216/24
resource_registry:
  OS::TripleO::Network::Ports::ControlPlaneVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_vip_ctlplane.yaml
  OS::TripleO::Network::Ports::ExternalVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_vip_external.yaml
  OS::TripleO::Network::Ports::InternalApiVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_vip_internal_api.yaml
  OS::TripleO::Network::Ports::StorageMgmtVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_vip_storage_mgmt.yaml
  OS::TripleO::Network::Ports::StorageVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_vip_storage.yaml
