---

- hosts: localhost
  gather_facts: true
  vars:
    tripleo_keystone_resources_admin_endpoint: http://192.168.24.25:35357
    tripleo_keystone_resources_admin_password: 6FztmMzAqnKoRX0ZbYkDwVfSb
    tripleo_keystone_resources_catalog_config: '{{ keystone_resources }}'
    tripleo_keystone_resources_cloud_name: overcloud-system-admin
    tripleo_keystone_resources_internal_endpoint: http://192.168.24.25:5000
    tripleo_keystone_resources_member_role_enabled: false
    tripleo_keystone_resources_public_endpoint: https://openstack.bne-home.net:13000
    tripleo_keystone_resources_region: regionOne
    tripleo_keystone_resources_service_project: service

  roles:
    - tripleo_keystone_resources
